# Generated by Django 4.2.4 on 2023-09-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('nit', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('observacion', models.TextField(verbose_name='Observaciones')),
                ('estado', models.CharField(default='1', max_length=1)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TiposCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carro', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=200)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('origendestino', models.CharField(default='', max_length=200, null=True)),
                ('valor_cobrar', models.PositiveBigIntegerField()),
                ('valor_pagar', models.PositiveBigIntegerField()),
                ('comentarios', models.TextField(default='')),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('Cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.clientes')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
                ('tipo_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.tiposcar')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('capacidad', models.PositiveSmallIntegerField(default=4)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.conductores')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.propietarios')),
                ('tipo_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.tiposcar')),
            ],
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_servicio', models.CharField(choices=[('0', 'ENTRADA'), ('1', 'SALIDA'), ('2', 'OTROS')], max_length=50)),
                ('estado', models.CharField(choices=[('0', 'PENDIENTE'), ('1', 'ASIGNADO'), ('2', 'EJECUTADO'), ('3', 'CANCELADO')], default='0', max_length=20)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('usuarios', models.TextField()),
                ('comentario', models.TextField()),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.clientes')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.placas')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.zona')),
            ],
        ),
        migrations.AddField(
            model_name='conductores',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa'),
        ),
    ]
