# Generated by Django 4.2.4 on 2023-08-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nit', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('cedula', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('nit', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('observacion', models.TextField(verbose_name='Observaciones')),
                ('fechacrea', models.DateField()),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('zona', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TiposCar',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tipo_carro', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=200)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('empresa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('codigo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Cliente', models.CharField(max_length=50)),
                ('tipo_carro', models.CharField(max_length=50)),
                ('valor_cobrar', models.PositiveBigIntegerField()),
                ('valor_pagar', models.PositiveBigIntegerField()),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('empresa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id_propietario', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('empresa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('capacidad', models.PositiveSmallIntegerField(default=4)),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.conductores')),
                ('empresa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.propietarios')),
                ('tipo_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.tiposcar')),
            ],
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('tipo_servicio', models.CharField(choices=[(0, 'ENTRADA'), (1, 'SALIDA'), (2, 'OTROS')], max_length=50)),
                ('estado', models.CharField(choices=[(0, 'PENDIENTE'), (1, 'ASIGNADO'), (2, 'EJECUTADO'), (3, 'CANCELADO')], default='PENDIENTE', max_length=20)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('usuarios', models.TextField()),
                ('comentario', models.TextField()),
                ('fechacrea', models.DateField(auto_now_add=True)),
                ('fechaupdate', models.DateField(auto_now=True)),
                ('usuariocrea', models.CharField(default='', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.clientes')),
                ('empresa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.placas')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.zona')),
            ],
        ),
        migrations.AddField(
            model_name='conductores',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.empresa'),
        ),
    ]
