# Generated by Django 4.2.4 on 2023-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuariocrea',
            field=models.CharField(default='', max_length=10),
        ),
    ]
