# Generated by Django 4.2.4 on 2023-09-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='estado',
            field=models.BooleanField(default=1),
        ),
    ]
