# Generated by Django 4.2.4 on 2023-08-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0002_empresa_estado_alter_empresa_usuariocrea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fechacrea',
            field=models.DateField(auto_now_add=True),
        ),
    ]
