# Generated by Django 4.2.4 on 2023-09-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0002_tarifa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietarios',
            name='nit',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
