# Generated by Django 4.2.4 on 2023-08-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0004_usuarioempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nit',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
