# Generated by Django 4.2.4 on 2023-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0005_alter_clientes_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='tarifa',
            name='Cliente',
            field=models.ManyToManyField(to='Operaciones.clientes'),
        ),
    ]
