# Generated by Django 4.2.4 on 2023-08-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0006_remove_tarifa_cliente_tarifa_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='comentarios',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='origendestino',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='Cliente',
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tipo_carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operaciones.tiposcar'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='Cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Operaciones.clientes'),
        ),
    ]
