# Generated by Django 4.2.4 on 2023-08-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operaciones', '0007_tarifa_comentarios_tarifa_origendestino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='origendestino',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
